fix: make the width 100% for the lti component and change the hc-name…
BrightspaceHypermediaComponents/foundation-components pull request #253
Opened 2021-06-21 18:59 UTC by alogan519

… component to no-wrap only when skeleton is set.

2021-06-22 13:50 UTC, maggiesazio approved these changes

2021-06-22 15:23 UTC, dbatiste commented on components/common/d2l-hc-name.js
> +			:host([skeleton]) {
It looks like this change would affect a bunch of things.  I presume that's what we want?

2021-06-22 15:23 UTC, dbatiste commented on features/lti/d2l-lti-activity.js
> +				margin-left: 0.8rem;
This will require adding the `RtlMixin` and adding a corresponding rtl selector to flip this whitespace.

Looks like there is only the one icon in this component... so this selector could probably be changed to `d2l-icon { ... }` and the `.icon` class could be avoided.

2021-06-22 18:32 UTC, zinabat requested changes
I would second Dave's RTLmixin suggestion before merging. Otherwise,

2021-06-22 23:45 UTC, zinabat commented on features/lti/d2l-lti-activity.js
> +					<iframe class="${this.iFrameWidth ? '' : 'content-frame-default-width'}" allow="microphone *; camera *; autoplay *" width="${this.iFrameWidth}px" height="${this.iFrameHeight}px" src="${this._lau
I'm approving this now, but normally when we add classes this way, we use the `classMap` directive: https://lit-html.polymer-project.org/guide/template-reference#classmap

2021-06-22 23:45 UTC, zinabat approved these changes

2021-06-23 00:55 UTC, alogan519 commented on features/lti/d2l-lti-activity.js
> +					<iframe class="${this.iFrameWidth ? '' : 'content-frame-default-width'}" allow="microphone *; camera *; autoplay *" width="${this.iFrameWidth}px" height="${this.iFrameHeight}px" src="${this._lau
oh nice that's perfect, thank you

2021-06-23 20:04 UTC, merged