After adding another condition focus is on new one
BrightspaceHypermediaComponents/foundation-components pull request #313
Opened 2021-09-17 17:59 UTC by ChrisLabattD2L

[DE45110](https://rally1.rallydev.com/#/357252275780d/custom/367300408400?detail=%2Fdefect%2F608843206171)

After clicking on the "Add another condition", the focus is now on the latest condition rather than remaining on the button previously clicked to improve the accessibility.

2021-09-21 14:34 UTC, BhamelinD2L requested changes
Because this is in updated, it will run every single time there is more than 1 condition and any aspect of the component changes. This means it will constantly focus the last condition any time you interact with any of the the attributes in the picker.

You should put the code changes under the add condition button handler, await updateComplete, and then focus.

2021-09-21 14:56 UTC, ChrisLabattD2L commented
> Because this is in updated(), it will run every single time there is more than 1 condition and any aspect of the component changes. This means it will constantly focus the last condition any time you interact with any of the the attributes in the picker.
> 
> You should put the code changes under the add condition button handler, await updateComplete, and then focus.

The changes I just pushed should function properly, let me know if there are any other changes you think are necessary 😄

2021-09-21 21:12 UTC, BhamelinD2L commented on features/discover/d2l-discover-rule-picker.js
> +		if (conditionOrgUnitIDList.length > 1) {
Is there a reason we need this check? What happens if we remove it?

2021-09-22 13:16 UTC, ChrisLabattD2L commented on features/discover/d2l-discover-rule-picker.js
> +		if (conditionOrgUnitIDList.length > 1) {
I included the check to reduce the risk of an error being caused due to the query selector not being able to find anything

2021-09-22 13:26 UTC, ChrisLabattD2L commented on features/discover/d2l-discover-rule-picker.js
> +		if (conditionOrgUnitIDList.length > 1) {
Tested it after removing it and it works the same, it was mainly put in as a precaution because it was previously in updated(), so it may not be necessary anymore.

2021-09-22 14:01 UTC, BhamelinD2L approved these changes

2021-09-22 14:29 UTC, merged