feat: d2l-discover-date-picker
BrightspaceHypermediaComponents/foundation-components pull request #329
Opened 2021-10-18 19:42 UTC by ChrisLabattD2L

Based on [US132158](https://rally1.rallydev.com/#/611579333303d/dashboard?detail=%2Fuserstory%2F610209547387)

The integration of the d2l-discover-date-picker component into the rule picker dialog will be a different PR

This PR will have to wait to be merged once [this PR](https://github.com/BrightspaceHypermediaComponents/foundation-components/pull/326) gets merged into master.

2021-11-03 15:40 UTC, BhamelinD2L commented on features/discover/test/d2l-discover-date-picker.test.js
> +		it('initialize default component', async() => {
nit: The text should read as a proper sentence. 'it initialize**s** the default component, 'it change**s** between single and range dates', etc

2021-11-03 15:44 UTC, BhamelinD2L requested changes
You should add a demo for the component so that it can be reviewed and tested in isolation so we can test and catch any problems now before we add the complexity of integration. Looks good so far though!

2021-11-08 17:11 UTC, BhamelinD2L requested changes

2021-11-08 17:11 UTC, BhamelinD2L commented on features/discover/d2l-discover-date-picker.js
> +					<d2l-input-date-range label="Date Range" child-labels-hidden label-hidden required start-value="${this.primaryDate}" end-value="${this.secondaryDate}" @change="${this._onRangeDateChange}"></d2l-
If just a line or two is huge like this, it's more readable to newline each attribute so that it doesn't need to be scrolled over to read

2021-11-08 17:11 UTC, BhamelinD2L commented on features/discover/d2l-discover-date-picker.js
> +}
This should be happening when you change the dropdown off of range. You're removing one of the dates, but the data doesn't reflect it has been removed. 

Currently if you set two dates, switch `range` to `before` and save, the last fired event will be the range and the user will not save what the UI reflects.

2021-11-08 17:11 UTC, BhamelinD2L commented on features/discover/test/d2l-discover-date-picker.test.js
> +			el._updateRulePicker();
Calling this function cheats the event and prevents you from finding the above noted bug. It doesn't adequately represent a real workflow.
In general try to avoid calling private functions in tests. It's much better to simulate user actions like modifying the select and awaiting changes whenever possible.

2021-11-08 19:10 UTC, ChrisLabattD2L commented on features/discover/d2l-discover-date-picker.js
> +	}
Thanks for pointing this out, I totally forgot to remove it!

2021-11-09 21:22 UTC, BhamelinD2L approved these changes
Looks great now. Thank you!

2021-11-09 21:23 UTC, merged