feat: Clabatt/us132160 integrate date picker
BrightspaceHypermediaComponents/foundation-components pull request #341
Opened 2021-11-04 18:46 UTC by ChrisLabattD2L

[US132160](https://rally1.rallydev.com/#/611579333303d/custom/367300408400?detail=%2Fuserstory%2F610210869893)

Dependent on [PR#329 feat: d2l-discover-date-picker ](https://github.com/BrightspaceHypermediaComponents/foundation-components/pull/329).

2021-11-11 21:54 UTC, BhamelinD2L requested changes

2021-11-11 21:54 UTC, BhamelinD2L commented on features/discover/d2l-discover-rule-picker.js
> +						<d2l-discover-date-picker
Is there a way we can base this on whether the type is actually date instead?

2021-11-11 21:54 UTC, BhamelinD2L commented on features/discover/d2l-discover-rule-picker.js
> +		rule.entities.forEach((condition, index) => {
There is a lot of nesting here and it's hitting a point where it's very difficult to manually run through the code. 
Like other places, guard clause the skip condition, see if you can use date instead of type, and simplify out the if/elses into 3 equal elseifs at the same level instead of nesting like this and it will really help.

2021-11-12 15:35 UTC, ChrisLabattD2L commented on features/discover/d2l-discover-attribute-picker.js
> +	}
By not awaiting the inner attribute picker, the [focus call](https://github.com/BrightspaceHypermediaComponents/foundation-components/blob/clabatt/US132160-integrate-date-picker/features/discover/d2l-discover-rule-picker.js#L455) that occurs when the user switches between condition types (specifically when it has to switch between the attribute and date picker) does not function properly as the component that is supposed to receive focus hasn't been rendered in yet and as a result, it doesn't get focused. This code was mainly added to make sure the focus shift is consistent with that before the date picker was integrated. This was the best way I was able to find in order to get the focus to work, if you have any suggestion or recommendation about other ways of handling this, just let me know!

2021-11-12 15:36 UTC, ChrisLabattD2L commented on features/discover/d2l-discover-date-picker.js
> +	}
See the comment I left for the previous question for the attribute picker. If need be, I can add comments to explain this, just lmk if you think that it's needed

2021-11-12 15:47 UTC, ChrisLabattD2L commented on features/discover/d2l-discover-rule-card.js
> +			if (!skipCondition) {
I've added the guard clauses, just note that `continue` doesn't work with `forEach`, you need to use `return` instead

2021-11-15 17:38 UTC, ChrisLabattD2L commented on features/discover/d2l-discover-rule-picker.js
> +						<d2l-discover-date-picker
So I've added a function that returns the type (string/date), but had to keep the original check as a secondary check in case the condition types had yet to be added in (which was causing many tests to fail)

2021-11-15 18:38 UTC, BhamelinD2L commented on features/discover/d2l-discover-attribute-picker.js
> +	}
I think we normally just await in the place it's actually necessary but I don't see a reason this wouldn't be fine. I'd clarify it in a small comment above the function if you can for future reference though, because it's unusual and not easy to tell why it's here at a glance. Same with the other(s)

2021-11-15 21:07 UTC, BhamelinD2L approved these changes
I'm happy with these changes, thank you!

2021-11-15 21:13 UTC, merged