feat: US132870 - Handle Resource Ids
BrightspaceHypermediaComponents/foundation-components pull request #366
Opened 2021-11-26 16:55 UTC by BhamelinD2L

This PR adjusts conditions to use a name/value object representation in place of a single value representing both.

Tested with live data as well as tests and updated demos.

[This PR requires this branch in the multi-select repo](https://github.com/BrightspaceUILabs/multi-select/pull/118). you can `npm install` this branch into your foundation-component repo, or you can link them both locally with BSI to manually test before merge. Consequently, this PR should have its package version of multi-select updated before release.

2021-11-26 17:03 UTC, BhamelinD2L commented on features/discover/mixins/discover-localization-mixin.js
> +	getCardTitle(rule) {
While adjusting the titles to use the .name properties that had been added with this PR, I pulled card title generation into this mixin so that the duplicated code between list and card is removed.

2021-11-26 19:58 UTC, ChrisLabattD2L requested changes
So I've started going through some of the code, but when I started testing it I was getting the following while using `DiscoverDev`:

![image](https://user-images.githubusercontent.com/71081906/143625276-413e1ecf-c414-4e0a-8242-a6c5e150fe8a.png)

The cards load in properly though, so it may be an issue with how the attribute picker is being passed the assignable attributes.

I'm gonna continue to look through your code, but thought you may wanna check this out while I do.

2021-11-26 19:58 UTC, ChrisLabattD2L commented on features/discover/test/d2l-discover-rule-picker.test.js
> +					{ properties: { id:'_fruit', type: 'Fruit', op: '$in', values: [{ name: 'apple', value: 'apple' }] } }
I won't comment this for every case, but does the new naming scheme mean that the tests we use should have `name: 'NAME_apple'` instead of just `name: 'apple'`?

2021-11-26 20:15 UTC, BhamelinD2L commented on features/discover/test/d2l-discover-rule-picker.test.js
> +					{ properties: { id:'_fruit', type: 'Fruit', op: '$in', values: [{ name: 'apple', value: 'apple' }] } }
> So I've started going through some of the code, but when I started testing it I was getting the following while using `DiscoverDev`:
> 
> ![image](https://user-images.githubusercontent.com/71081906/143625276-413e1ecf-c414-4e0a-8242-a6c5e150fe8a.png)
> 
> The cards load in properly though, so it may be an issue with how the attribute picker is being passed the assignable attributes.
> 
> I'm gonna continue to look through your code, but thought you may wanna check this out while I do.

It did look like this for some period of commits, make sure your instance is fully updated? I'd expect the test to catch that the name on the cards isn't correct. I cleaned out my BSI and re-linked and can't repro this issue.

2021-11-26 20:16 UTC, BhamelinD2L commented on package.json
> +    "@brightspace-ui-labs/multi-select": "git+https://github.com/BrightspaceUILabs/multi-select.git#US132870-named_values",
Yeah. It'll fail the tests without this, it's noted in the PR request it will be updated.

2021-11-26 20:20 UTC, dkong-d2l commented on features/discover/test/test-utils.js
> +		value
If you use the name of a scoped variable as an object name, the value of the variable is used as the value of the object property!

2021-11-26 20:21 UTC, BhamelinD2L commented on features/discover/test/test-utils.js
> +		value
We need tests to ensure the name is being used, not the value. Having them be different is useful for that reason.

However, in real data that isn't representing IDs, the name and value match. Making them different doesn't really matter in cases where a difference in name and value isn't what the test data is testing for.

2021-11-26 20:23 UTC, BhamelinD2L commented on features/discover/test/d2l-discover-rules.test.js
> +				{ properties: { id:'_orgRole', type: 'Role', values: [{ name: 'worker', value: 'worker' }], op: '$in' } }
It doesn't really matter for the purposes of the test, and this format emulates real data, so I went with the emulation of real data. I don't think it matters in this case, we just need a rule to exist for the test.

2021-11-26 20:24 UTC, dkong-d2l commented on features/discover/test/d2l-discover-rules.test.js
> +				{ properties: { id:'_orgRole', type: 'Role', values: [{ name: 'worker', value: 'worker' }], op: '$in' } }
Given that the name of the test is `it(hides add rule when a rule already exists)`, I'm guessing that it does not really matter what the value is called...

2021-11-26 20:33 UTC, ChrisLabattD2L commented on features/discover/test/d2l-discover-rule-picker.test.js
> +					{ properties: { id:'_fruit', type: 'Fruit', op: '$in', values: [{ name: 'apple', value: 'apple' }] } }
Deleting and then reinstalling the node modules fixed this issue

2021-11-26 20:43 UTC, dkong-d2l commented on features/discover/d2l-discover-rule-picker.js
> +			const dateVal = (condition.properties.values && condition.properties.values[0]) || condition.entities[0].properties.value;
This is curious...  Why is `dateVal` sometimes from `condition.properties.values[0]` and sometimes from `condition.entities[0].properties.value`?  Now that we're committing to named values, you'd think it would just be from one source?

2021-11-26 21:00 UTC, BhamelinD2L commented on features/discover/d2l-discover-rule-picker.js
> +			const dateVal = (condition.properties.values && condition.properties.values[0]) || condition.entities[0].properties.value;
I ended up changing this to match the way it behaves from `$in` where it can 
A) take data directly from the siren response as an entity as well as
B) the format passed by the `d2l-discover-rules` component.

There's no reason to handle things via A, as all rules sent to this component are pre formatted by the rule picker to be in line with what is sent out to the BFF on save, so I will remove that entity stuff. Will cause some significant test updates in the picker tests.

2021-11-29 15:37 UTC, ChrisLabattD2L approved these changes
Looks good to me, I added a comment regarding moving `rels` and other reused constants to their own file like you had done with the tests, but it doesn't have to be done in this PR. It was more just a clean-up suggestion for the future.

2021-11-29 15:37 UTC, ChrisLabattD2L commented on features/discover/d2l-discover-rules.js
> +	rule: 'https://discovery.brightspace.com/rels/rule',
Doesn't have to be done in this PR, but I think it would be worth moving `rels` and other reoccurring constants to a separate file like you did with the [test-utils.js](https://github.com/BrightspaceHypermediaComponents/foundation-components/blob/bhamelind2l/us132870-handle-resource-ids/features/discover/test/test-utils.js) file.

2021-11-29 17:14 UTC, merged