US136651: create hypermedia filter component
BrightspaceHypermediaComponents/foundation-components pull request #438
Opened 2022-03-14 16:33 UTC by tenbradley

### Context
[US136651](https://rally1.rallydev.com/#/?detail=/userstory/627974778725&fdp=true)

2022-03-18 15:29 UTC, ChrisLabattD2L requested changes
Pretty much just some nitpicks from my end.

2022-03-18 15:29 UTC, ChrisLabattD2L commented on components/common/d2l-hc-filter.js
> +				if (this.selected.get(element.valueKey) !== element.selected) updated = true;
This could easily just be `updated = (this.selected.get(element.valueKey) !== element.selected)`, you don't really need the if

2022-03-18 15:29 UTC, ChrisLabattD2L commented on components/common/d2l-hc-filter.js
> +		this.values = undefined;
You don't actually have to initialize title and values to be `undefined` since they will already be `undefined` at this point.

2022-03-18 15:29 UTC, ChrisLabattD2L commented on components/common/d2l-hc-filter.js
> +		if (!this.title || !this.values) return html``;
You don't actually have to `return html'';` here, you can just do `return;`

2022-03-18 15:29 UTC, ChrisLabattD2L commented on components/common/test/d2l-hc-filter.test.js
> +// };
If we don't end up needing this, you might as well remove it, it isn't hard to readd it later if it does end up being needed.

2022-03-21 18:17 UTC, tenbradley commented on components/common/d2l-hc-filter.js
> +				if (this.selected.get(element.valueKey) !== element.selected) updated = true;
Changed to `updated = updated || (this.selected.get(element.valueKey) !== element.selected)`

2022-03-21 18:46 UTC, ChrisLabattD2L requested changes
A few little nitpicks, but I did have one more important question which is, what happens if we have more than one value with the same name? Is this a situation that we should be dealing with? Or are we going under the assumption that there'll never be a situation in which this happens?

2022-03-21 18:46 UTC, ChrisLabattD2L commented on components/common/d2l-hc-filter.js
> +				updated = updated || this.selected.get(element.valueKey) !== element.selected;
Since you set updated to false just before this, I don't think you'll actually need the `updated ||` part

2022-03-21 18:46 UTC, ChrisLabattD2L commented on components/common/test/d2l-hc-filter.test.js
> +import { clearStore } from '@brightspace-hmc/foundation-engine/state/HypermediaState.js';
Since the hypermedia aspect was removed, I don't know if we still need to use `clearStore`

2022-03-21 19:05 UTC, ChrisLabattD2L commented on components/common/d2l-hc-filter.js
> +import { HypermediaStateMixin } from '@brightspace-hmc/foundation-engine/framework/lit/HypermediaStateMixin.js';
Also forgot to ask, do we still need this mixin?

2022-03-21 20:00 UTC, tenbradley commented on components/common/d2l-hc-filter.js
> +				updated = updated || this.selected.get(element.valueKey) !== element.selected;
There could be multiple changes. The `updated ||` should account for if there are multiple items in the changes array but some are unchanged.

2022-03-21 20:04 UTC, tenbradley commented on components/common/d2l-hc-filter.js
> +import { HypermediaStateMixin } from '@brightspace-hmc/foundation-engine/framework/lit/HypermediaStateMixin.js';
I'm thinking about this. I think it should be safe to remove this. I'll try that out.

2022-03-21 20:07 UTC, ChrisLabattD2L commented on components/common/d2l-hc-filter.js
> +				updated = updated || this.selected.get(element.valueKey) !== element.selected;
You're absolutely correct, forgot it was in a loop oops

2022-03-22 13:46 UTC, tenbradley commented on components/common/test/d2l-hc-filter.test.js
> +			element.updateValues(threeCourses);
I potentially could get rid of the updateValues function. Or at the very least change it to a settor. While it's not being used for it currently, I forsee this function being updated to handle dynamic filters. But based on it's use now, I can get rid of it.

2022-03-22 15:05 UTC, ChrisLabattD2L approved these changes
Looks good! Thanks for making those changes!

2022-03-22 18:00 UTC, merged